[package]
name = "token"
type = "contract"
authors = [""]
compiler_version = ">=0.33.0"

[dependencies]
# aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.51.1", directory="noir-projects/aztec-nr/aztec" }
# authwit = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.51.1", directory="noir-projects/aztec-nr/authwit"}
# compressed_string = {git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.51.1", directory="noir-projects/aztec-nr/compressed-string"}
token_contract = {git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.51.1", directory="noir-projects/noir-contracts/contracts/token_contract"}